### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dz0** [dz0/inlined_calls_explorer#1]
General issue list for myself :)

- [ ] first func to "inlined" div (because want "expand all")
- [x]  allow direct linking to _html/static/* in exported
- [ ]  allow to inject config / watch_helpers to  watch eval namespace 
- [x]  ordiranry lines toggling with fade out/in
- [x]  smart toggling for nested    (according to first element state)  

- [x] fix nested functions (for toggling and displaying) 

- [ ] test_simple skips "A"

- [ ]  menu/list of watches  

- [ ]  bug: ignoring in A:  c = C()  #WATCH_AFTER: c  (calling C breaks watches :/ )
